package placement;
import java.time.LocalDateTime;
import user.Student;

/**
 * Represents a single application submitted by a {@link Student} for an {@link Internship}.
 * This class tracks the application's status, from submission through
 * approval, acceptance, or withdrawal.
 *
 * @version 1.0
 */
public class Application {
    private final int applicationID;
    private final Student student;
    private final Internship internship; // same
    private ApplicationStatus status;
    private final LocalDateTime submittedAt;

    private boolean acceptedByStudent;
    //student can manually rescind their application / auto withdraw upon accepting an intern
    private boolean studentWithdrawalRequested;
    private boolean careerStaffWithdrawalAccepted;

    /**
     * Constructs a new Application instance.
     * This is used when a student creates a new application.
     *
     * @param aid The unique ID for the application, generated by {@link datastore.ApplicationStore}.
     * @param s The {@link Student} who is applying.
     * @param i The {@link Internship} being applied for.
     */
    public Application(int aid, Student s, Internship i){
        this.applicationID = aid;
        // ^^^ we can either import ApplicationStore here and call generateID or just pass in through constructor, I opted for the latter
        this.student = s;
        this.internship = i;
        this.status = ApplicationStatus.PENDING;
        this.acceptedByStudent = false;
        this.studentWithdrawalRequested = false; //I believe this only applies to student manually withdrawing, if student accepts another one, it should all be withdrawn regardless of this value
        this.careerStaffWithdrawalAccepted = false;
        this.submittedAt = LocalDateTime.now();

    }

    /**
     * Constructs an Application instance from existing data.
     * This is used by {@link initiation.ApplicationBuilder} when loading data from a file.
     *
     * @param aid The application's unique ID.
     * @param s The applying {@link Student}.
     * @param i The target {@link Internship}.
     * @param status The current {@link ApplicationStatus}.
     * @param submittedAt The original submission timestamp.
     * @param acceptedByStudent Whether the student has accepted the offer.
     * @param studentWithdrawalRequested Whether the student has requested to withdraw.
     * @param careerStaffWithdrawalAccepted Whether staff has approved the withdrawal.
     */
    public Application(int aid, Student s, Internship i, ApplicationStatus status, LocalDateTime submittedAt,
                       boolean acceptedByStudent, boolean studentWithdrawalRequested,
                       boolean careerStaffWithdrawalAccepted){
        this.applicationID = aid;
        this.student = s;
        this.internship = i;
        this.status = status; // Corrected: was PENDING, should be 'status' from param
        this.acceptedByStudent = acceptedByStudent;
        this.studentWithdrawalRequested = studentWithdrawalRequested;
        this.careerStaffWithdrawalAccepted = careerStaffWithdrawalAccepted;
        this.submittedAt = submittedAt;

    }

    //GETS
    /** @return The unique application ID. */
    public int getApplicationID() { return applicationID; }
    /** @return The {@link Student} who submitted this application. */
    public Student getStudent() { return student; }
    /** @return The {@link Internship} this application is for. */
    public Internship getInternship() { return internship; }
    /** @return The current {@link ApplicationStatus} (PENDING, SUCCESSFUL, etc.). */
    public ApplicationStatus getStatus() { return status; }
    /** @return The timestamp when the application was submitted. */
    public LocalDateTime getSubmittedAt() { return submittedAt; }
    /** @return {@code true} if the student has accepted this offer, {@code false} otherwise. */
    public boolean isAcceptedByStudent() { return acceptedByStudent; }
    /** @return {@code true} if the student has requested to withdraw, {@code false} otherwise. */
    public boolean isStudentWithdrawalRequested() { return studentWithdrawalRequested; }
    /** @return {@code true} if Career Staff has approved the withdrawal, {@code false} otherwise. */
    public boolean isCareerStaffWithdrawalAccepted() { return careerStaffWithdrawalAccepted; }

    //SETTERS
    /**
     * Internal method to change the application's status.
     * @param status The new {@link ApplicationStatus} to set.
     */
    private void setApplicationStatus(ApplicationStatus status){
        this.status = status;
    }

    /**
     * Forcibly withdraws the application.
     * This is used when a student accepts another offer.
     */
    public void forceWithdraw(){
        this.status = ApplicationStatus.WITHDRAWN;
    }

    //CareerStaff related actions (setters with restrictions)
    /** @return The current {@link ApplicationStatus}. (Duplicate of getStatus()) */
    public ApplicationStatus  getApplicationStatus() {
        return status;
    }

    /**
     * Sets the application status to SUCCESSFUL.
     * Typically called by a {@link user.CompanyRep}.
     */
    public void setSuccessful(){
        setApplicationStatus(ApplicationStatus.SUCCESSFUL);
    }

    /**
     * Sets the application status to UNSUCCESSFUL.
     * Typically called by a {@link user.CompanyRep}.
     */
    public void setUnsuccessful(){setApplicationStatus(ApplicationStatus.UNSUCCESSFUL);
    }

    /**
     * Approves a student's withdrawal request.
     * Called by {@link user.CareerStaff}. If the student had already accepted
     * this offer, it also frees up a slot in the internship.
     */
    public void approveWithdrawal(){
        boolean wasSlotFilled = (this.status == ApplicationStatus.ACCEPTED);

        this.careerStaffWithdrawalAccepted = true;
        this.setApplicationStatus(ApplicationStatus.WITHDRAWN);
        if (wasSlotFilled && this.internship != null) {
            this.internship.removeFilledSlot();
        }
    }

    /**
     * Rejects a student's withdrawal request.
     * Called by {@link user.CareerStaff}.
     */
    public void rejectWithdrawal() {
        if (this.studentWithdrawalRequested) {
            this.studentWithdrawalRequested = false;
        }
    }


    //Student related actions
    /**
     * Marks this application as having a pending withdrawal request
     * from the student.
     */
    public void setStudentWithdrawalRequested() {
        this.studentWithdrawalRequested = true;
    }

    /**
     * Marks this application as accepted by the student.
     * This is the final step in securing the internship.
     */
    public void studentAccept(){
        this.acceptedByStudent = true;
        this.setApplicationStatus(ApplicationStatus.ACCEPTED);
    }
}